package Interfaz;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import proyectojava.Cliente;
import proyectojava.Evento;
import proyectojava.GestionClientes;
import proyectojava.Reservas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author icesa
 */
public class VentanaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdmin
     */
    public VentanaAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de admin");
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("Gestión de admin");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Gestión de eventos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("Consultar eventos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("Consultar usuarios");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setText("Consultar reservas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setText("CERRAR SESIÓN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(242, 242, 242))
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Botón gestión de eventos
        new Ventana_Gestion().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Botón consultar eventos
        
        JFrame panelConsultarEvento = new JFrame("Consultar eventos");
            JPanel panelPantallaConsultarEvento = new JPanel();
            panelPantallaConsultarEvento.setLayout(new BoxLayout(panelPantallaConsultarEvento, BoxLayout.Y_AXIS));
            panelConsultarEvento.setSize(300, 200);
            panelConsultarEvento.setLocationRelativeTo(this); 

            ArrayList<Evento> eventosRecuperados = GestionClientes.cargarEventos();
            ArrayList<String> recuperadosArray = new ArrayList<>();

        for (Evento evento : eventosRecuperados) {
            String clave = evento.getTitulo(); 
            recuperadosArray.add(clave);
            System.out.println(recuperadosArray);
            System.out.println("Clave: " + clave);
        }

        JList<String> lista = new JList<>(recuperadosArray.toArray(new String[0]));
        JScrollPane scroll = new JScrollPane(lista);
        lista.addMouseListener(new MouseAdapter() {
                 public void mouseClicked(MouseEvent event) {
                    if (event.getClickCount() == 2) {
                      int index = lista.locationToIndex(event.getPoint());
                        if (index >= 0) {
                           Evento seleccionado = eventosRecuperados.get(index);
                           
                           ImageIcon icono = new ImageIcon("/resources/imagen_negra");
                           File archivo = new File(seleccionado.getRutaImagen()); 
                           if (archivo.exists()) {
                             icono = new ImageIcon(archivo.getPath());
                           } else {
                           System.out.println("La imagen no existe en: " + archivo.getAbsolutePath());
                           }
                           
                           JOptionPane.showMessageDialog(null,"Nombre: " + seleccionado.getTitulo() + "\n"
                                   + "Tipo: " + seleccionado.getTipo() + "\nCiudad: " + seleccionado.getDireccion().getCiudad() + "\n"
                                   + "Calle: " + seleccionado.getDireccion().getCalle() + "\nNúmero: " + seleccionado.getDireccion().getNumero() + "\n"
                                   + "Código postal: " + seleccionado.getDireccion().getCp() + "\nPrecio: " + seleccionado.getPrecio() + "\n"
                                   + "Calificación: " + seleccionado.getCalificacion() + "\n\n","Consultar evento: " + seleccionado.getTitulo(),JOptionPane.PLAIN_MESSAGE, icono);
            }
        }
    }
});

            panelConsultarEvento.add(scroll);
            panelConsultarEvento.setVisible(true);

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Botón consultar usuarios
        
        JFrame panelConsultarUsuarios = new JFrame("Usuarios");
            JPanel panelPantallaConsultarUsuarios = new JPanel();
            panelPantallaConsultarUsuarios.setLayout(new BoxLayout(panelPantallaConsultarUsuarios, BoxLayout.Y_AXIS));
            panelConsultarUsuarios.setSize(300, 200);
            panelConsultarUsuarios.setLocationRelativeTo(this); 

            HashMap<String, Cliente> recuperados = GestionClientes.cargarClientes();
            ArrayList<Cliente> recuperadosArray = new ArrayList<>(recuperados.values());
            
            String[] nombresClientes = recuperadosArray.stream()
            .map(cliente -> cliente.getCorreo()) 
            .toArray(String[]::new);

            JList<String> lista = new JList<>(nombresClientes);
            JScrollPane scroll = new JScrollPane(lista);
            lista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);


            lista.addMouseListener(new MouseAdapter() {
                 public void mouseClicked(MouseEvent event) {
                    if (event.getClickCount() == 2) {
                      int index = lista.locationToIndex(event.getPoint());
                        if (index >= 0) {
                           Cliente seleccionado = recuperadosArray.get(index);
                           
                           JOptionPane.showMessageDialog(null,"Nombre: " + seleccionado.getNombre() + "\nCorreo: " + seleccionado.getCorreo() + "\n"
                                   + "Teléfono: " + seleccionado.getTelefono() + "\nCiudad: " + seleccionado.getDireccion().getCiudad() + "\n"
                                   + "Calle: " + seleccionado.getDireccion().getCalle() + "\nNúmero: " + seleccionado.getDireccion().getNumero() + "\n"
                                   + "Código postal: " + seleccionado.getDireccion().getCp(), "Consultar: " + seleccionado.getNombre(), JOptionPane.PLAIN_MESSAGE);

            }
        }
    }
});

                           panelConsultarUsuarios.add(scroll);
                           panelConsultarUsuarios.setVisible(true);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Botón consultar reservas
        
        JFrame panelConsultarReservas = new JFrame("Usuarios");
            JPanel panelPantallaConsultarReservas = new JPanel();
            panelPantallaConsultarReservas.setLayout(new BoxLayout(panelPantallaConsultarReservas, BoxLayout.Y_AXIS));
            panelConsultarReservas.setSize(300, 200);
            panelConsultarReservas.setLocationRelativeTo(this); 

            HashMap<String, Cliente> recuperados = GestionClientes.cargarClientes();
            ArrayList<Cliente> recuperadosArray = new ArrayList<>(recuperados.values());
            
            String[] nombresClientes = recuperadosArray.stream()
            .map(cliente -> cliente.getCorreo()) 
            .toArray(String[]::new);

            JList<String> lista = new JList<>(nombresClientes);
            JScrollPane scroll = new JScrollPane(lista);
            lista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
            


            lista.addMouseListener(new MouseAdapter() {
                 public void mouseClicked(MouseEvent event) {
                    if (event.getClickCount() == 2) {
                      int index = lista.locationToIndex(event.getPoint());
                        if (index >= 0) {
                           Cliente seleccionado = recuperadosArray.get(index);
                           
                           ArrayList<Reservas> reservas = seleccionado.getListaReservas();
                StringBuilder mensaje = new StringBuilder();
                for (Reservas i : reservas) {
                    mensaje.append("- ").append(i.getEvento().getTitulo()).append("\n");
                }

                           
                           JOptionPane.showMessageDialog(null,"Reservas: \n" + mensaje,"Reservas de: " + seleccionado.getNombre(), JOptionPane.PLAIN_MESSAGE);

            }
        }
    }
});

                           panelConsultarReservas.add(scroll);
                           panelConsultarReservas.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Botón cerrar sesión
        
        new VentanaIniciar().setVisible(true);
        dispose();
        GestionClientes.setAdminActivo(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
