/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.util.ArrayList;
import proyectojava.Evento;
import static proyectojava.GestionClientes.accionBotonEventosBusqueda;
import static proyectojava.GestionClientes.botonEventosBusqueda;

/**
 *
 * @author pablo
 */
public class Ventana_Eventos extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Eventos
     */
    public Ventana_Eventos(ArrayList<Evento> eventos) {
        this.listaEventos = eventos;
        initComponents();
        botonEventosBusqueda(this.listaEventos, botonEvento1, botonEvento2, botonEvento3, botonEvento4, botonEvento5, botonEvento6, botonEvento7, botonEvento8, botonEvento9, this.pagina);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonEvento1 = new javax.swing.JButton();
        botonEvento2 = new javax.swing.JButton();
        botonEvento3 = new javax.swing.JButton();
        botonEvento4 = new javax.swing.JButton();
        botonEvento5 = new javax.swing.JButton();
        botonEvento6 = new javax.swing.JButton();
        botonEvento7 = new javax.swing.JButton();
        botonEvento8 = new javax.swing.JButton();
        botonEvento9 = new javax.swing.JButton();
        campoPagina = new javax.swing.JLabel();
        botonAtras = new javax.swing.JToggleButton();
        botonAdelante = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("EVENTOS:");

        botonEvento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEvento1ActionPerformed(evt);
            }
        });

        botonEvento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEvento2ActionPerformed(evt);
            }
        });

        botonEvento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEvento3ActionPerformed(evt);
            }
        });

        botonEvento4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEvento4ActionPerformed(evt);
            }
        });

        botonEvento5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEvento5ActionPerformed(evt);
            }
        });

        botonEvento6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEvento6ActionPerformed(evt);
            }
        });

        botonEvento7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEvento7ActionPerformed(evt);
            }
        });

        botonEvento8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEvento8ActionPerformed(evt);
            }
        });

        botonEvento9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEvento9ActionPerformed(evt);
            }
        });

        campoPagina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoPagina.setText("0");
        campoPagina.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonAtras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonAtras.setText("<");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonAdelante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonAdelante.setText(">");
        botonAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdelanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(botonAtras)
                                .addGap(4, 4, 4)
                                .addComponent(botonAdelante))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botonEvento3, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonEvento2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonEvento4, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonEvento5, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonEvento6, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonEvento7, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonEvento8, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonEvento9, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEvento2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEvento3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEvento4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEvento5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEvento6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEvento7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEvento8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEvento9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAdelante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoPagina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEvento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEvento1ActionPerformed
        accionBotonEventosBusqueda(this.listaEventos, this.pagina, 0, this);
    }//GEN-LAST:event_botonEvento1ActionPerformed

    private void botonEvento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEvento2ActionPerformed
        accionBotonEventosBusqueda(this.listaEventos, this.pagina, 1, this);
    }//GEN-LAST:event_botonEvento2ActionPerformed

    private void botonEvento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEvento3ActionPerformed
        accionBotonEventosBusqueda(this.listaEventos, this.pagina, 2, this);
    }//GEN-LAST:event_botonEvento3ActionPerformed

    private void botonEvento4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEvento4ActionPerformed
        accionBotonEventosBusqueda(this.listaEventos, this.pagina, 3, this);
    }//GEN-LAST:event_botonEvento4ActionPerformed

    private void botonEvento5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEvento5ActionPerformed
        accionBotonEventosBusqueda(this.listaEventos, this.pagina, 4, this);
    }//GEN-LAST:event_botonEvento5ActionPerformed

    private void botonEvento6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEvento6ActionPerformed
        accionBotonEventosBusqueda(this.listaEventos, this.pagina, 5, this);
    }//GEN-LAST:event_botonEvento6ActionPerformed

    private void botonEvento7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEvento7ActionPerformed
        accionBotonEventosBusqueda(this.listaEventos, this.pagina, 6, this);
    }//GEN-LAST:event_botonEvento7ActionPerformed

    private void botonEvento8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEvento8ActionPerformed
        accionBotonEventosBusqueda(this.listaEventos, this.pagina, 7, this);
    }//GEN-LAST:event_botonEvento8ActionPerformed

    private void botonEvento9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEvento9ActionPerformed
        accionBotonEventosBusqueda(this.listaEventos, this.pagina, 8, this);
    }//GEN-LAST:event_botonEvento9ActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        if (this.pagina > 0){
            this.pagina -= 1;
            campoPagina.setText(this.pagina + "");
            botonEventosBusqueda(this.listaEventos, botonEvento1, botonEvento2, botonEvento3, botonEvento4, botonEvento5, botonEvento6, botonEvento7, botonEvento8, botonEvento9, this.pagina);}
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdelanteActionPerformed
        if (this.pagina < 5){
            this.pagina += 1;
            campoPagina.setText(this.pagina + "");
            botonEventosBusqueda(this.listaEventos, botonEvento1, botonEvento2, botonEvento3, botonEvento4, botonEvento5, botonEvento6, botonEvento7, botonEvento8, botonEvento9, this.pagina);}
    }//GEN-LAST:event_botonAdelanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<Evento> eventos = new ArrayList<>();
                new Ventana_Eventos(eventos).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonAdelante;
    private javax.swing.JToggleButton botonAtras;
    private javax.swing.JButton botonEvento1;
    private javax.swing.JButton botonEvento2;
    private javax.swing.JButton botonEvento3;
    private javax.swing.JButton botonEvento4;
    private javax.swing.JButton botonEvento5;
    private javax.swing.JButton botonEvento6;
    private javax.swing.JButton botonEvento7;
    private javax.swing.JButton botonEvento8;
    private javax.swing.JButton botonEvento9;
    private javax.swing.JLabel campoPagina;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private int pagina = 0;
    private ArrayList<Evento> listaEventos;
}
