package Interfaz;

import java.awt.Component;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import proyectojava.Evento;
import proyectojava.GestionClientes;
import static proyectojava.GestionClientes.leerEntero;
import static proyectojava.GestionClientes.leerFecha;
import static proyectojava.GestionClientes.leerLong;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author icesa
 */
public class Ventana_Gestion extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Gestion
     */
    
    private JTextField campoAnadirTitulo;
    private JTextField campoAnadirTipo;
    private JTextField campoAnadirCalle;
    private JTextField campoAnadirNumero;
    private JTextField campoAnadirCiudad;
    private JTextField campoAnadirCp;
    private JTextField campoAnadirPrecio;
    private JTextField campoAnadirFecha;
    private JButton botonImagenEvento;
    private JButton botonModificarImagen;
    private File imagenOriginal;
    private File imagenCambiada;
    private String nombre;
    private String extension;
    
    public Ventana_Gestion() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Gestión de eventos");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Boton 1: Añadir evento
        
        campoAnadirTitulo = new JTextField(10);
        campoAnadirTipo = new JTextField(10);
        campoAnadirCiudad = new JTextField(10);
        campoAnadirCalle = new JTextField(10);
        campoAnadirNumero = new JTextField(10);
        campoAnadirCp = new JTextField(10);
        campoAnadirPrecio = new JTextField(10);
        campoAnadirFecha = new JTextField(10);
        botonImagenEvento = new JButton("Añadir imagen");

        JPanel panelAnadirEvento = new JPanel();
        panelAnadirEvento.setLayout(new BoxLayout(panelAnadirEvento, BoxLayout.Y_AXIS)); 
        panelAnadirEvento.add(new JLabel("Título: "));
        panelAnadirEvento.add(campoAnadirTitulo);
        panelAnadirEvento.add(Box.createVerticalStrut(10));  
        panelAnadirEvento.add(new JLabel("Tipo:"));
        panelAnadirEvento.add(campoAnadirTipo);
        panelAnadirEvento.add(Box.createVerticalStrut(10)); 
        panelAnadirEvento.add(new JLabel("Ciudad:"));
        panelAnadirEvento.add(campoAnadirCiudad);
        panelAnadirEvento.add(Box.createVerticalStrut(10)); 
        panelAnadirEvento.add(new JLabel("Calle:"));
        panelAnadirEvento.add(campoAnadirCalle);
        panelAnadirEvento.add(Box.createVerticalStrut(10)); 
        panelAnadirEvento.add(new JLabel("Numero:"));
        panelAnadirEvento.add(campoAnadirNumero);
        panelAnadirEvento.add(Box.createVerticalStrut(10)); 
        panelAnadirEvento.add(new JLabel("Codigo postal:"));
        panelAnadirEvento.add(campoAnadirCp);
        panelAnadirEvento.add(Box.createVerticalStrut(10)); 
        panelAnadirEvento.add(new JLabel("Precio:"));
        panelAnadirEvento.add(campoAnadirPrecio);
        panelAnadirEvento.add(Box.createVerticalStrut(10));
        panelAnadirEvento.add(new JLabel("Fecha:"));
        panelAnadirEvento.add(campoAnadirFecha);
        panelAnadirEvento.add(Box.createVerticalStrut(20));
        panelAnadirEvento.add(botonImagenEvento);
        panelAnadirEvento.add(Box.createVerticalStrut(10));
        
        botonImagenEvento.addActionListener(i -> {
         JFileChooser selector = new JFileChooser();
        selector.setDialogTitle("Selecciona una imagen");
        selector.setAcceptAllFileFilterUsed(false);
        selector.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png", "gif"));

        int resultado = selector.showOpenDialog(null);
        
        

        if (resultado == JFileChooser.APPROVE_OPTION) {
            imagenOriginal = selector.getSelectedFile();
        }     
     });
        
        
        
        
        int resultado = JOptionPane.showConfirmDialog(null, panelAnadirEvento, "Añadir evento", JOptionPane.OK_CANCEL_OPTION);
        String titulo = campoAnadirTitulo.getText();
        String tipo = campoAnadirTipo.getText();
        String calle = campoAnadirCalle.getText();
        String ciudad = campoAnadirCiudad.getText();     
        String fecha = campoAnadirFecha.getText();


        
        if (resultado == JOptionPane.OK_OPTION) {
            Integer numero = leerEntero(campoAnadirNumero, this, " Error en el formato del Numero\nPor favor vuelva a introducir los datos.");
            if (numero == null) return;
            numero = leerEntero(campoAnadirCp, this, " Error en el formato del Codigo Postal\nPor favor vuelva a introducir los datos.");
            if (numero == null) return;
            Long numero2 = leerLong(campoAnadirPrecio, this, " Error en el formato del Precio\nPor favor vuelva a introducir los datos.");
            if (numero2 == null) return;
            
           try {
                BufferedImage original = ImageIO.read(imagenOriginal);
                Image imagenEscalada = original.getScaledInstance(150, 150, Image.SCALE_SMOOTH);

                BufferedImage imagenFinal = new BufferedImage(150, 150, original.getType() == 0 ? BufferedImage.TYPE_INT_RGB : original.getType());
                Graphics2D g2d = imagenFinal.createGraphics();
                g2d.drawImage(imagenEscalada, 0, 0, null);
                g2d.dispose();

                File carpetaDestino = new File("resources");
                if (!carpetaDestino.exists()) carpetaDestino.mkdirs();

                nombre = imagenOriginal.getName();
                System.out.println(nombre);
                extension = nombre.substring(nombre.lastIndexOf('.') + 1);

                File archivoDestino = new File(carpetaDestino, nombre); // ("." + extension)
                ImageIO.write(imagenFinal, extension, archivoDestino);

       //         JOptionPane.showMessageDialog(null, "Imagen escalada y guardada correctamente en:\n" + archivoDestino.getAbsolutePath());
            } catch (IOException o) {
                JOptionPane.showMessageDialog(null, "Error al procesar la imagen:\n" + o.getMessage());
            }

            JOptionPane.showMessageDialog(this, 
            "Evento registrado correctamente",
            "Evento registrado",
            JOptionPane.INFORMATION_MESSAGE);
            
            Evento evento = registrarEvento();
            ArrayList<Evento> recuperadosArrayEventos = GestionClientes.cargarEventos();
            recuperadosArrayEventos.add(evento);
            GestionClientes.guardarEventos(recuperadosArrayEventos);
            System.out.println(recuperadosArrayEventos);
            
            
        } else if(resultado == JOptionPane.OK_OPTION && (titulo.isEmpty() || tipo.isEmpty() || calle.isEmpty() || ciudad.isEmpty() || fecha.isEmpty())){
        JOptionPane.showMessageDialog(this,"Datos no introducidos", "Por favor, rellene los datos", JOptionPane.INFORMATION_MESSAGE);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Boton 2: Eliminar evento
        
        JFrame panelEliminarEvento = new JFrame("Eliminar evento");
            JPanel panelPantallaEliminarEvento = new JPanel();
            panelPantallaEliminarEvento.setLayout(new BoxLayout(panelPantallaEliminarEvento, BoxLayout.Y_AXIS));
            panelEliminarEvento.setSize(300, 200);
            panelEliminarEvento.setLocationRelativeTo(this); 
            
        
            ArrayList<Evento> eventosRecuperados = GestionClientes.cargarEventos();
            ArrayList<String> recuperadosArray = new ArrayList<>();
            

        for (Evento evento : eventosRecuperados) {
            String clave = evento.getTitulo(); 
            recuperadosArray.add(clave);
            System.out.println(recuperadosArray);
            System.out.println("Clave: " + clave);
        }

        JList<String> lista = new JList<>(recuperadosArray.toArray(new String[0]));
        JScrollPane scroll = new JScrollPane(lista);
        lista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        lista.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent event) {
                if (event.getClickCount() == 2) {
                    int index = lista.locationToIndex(event.getPoint());
                    if (index >= 0) {
                        Evento seleccionado = eventosRecuperados.get(index);
                        
                        panelPantallaEliminarEvento.removeAll();
                                              
                        panelPantallaEliminarEvento.add(new JLabel("¿Estás seguro que deseas eliminar el evento " + seleccionado.getTitulo() + '?'));
                        
                        int resultado = JOptionPane.showConfirmDialog(null, panelPantallaEliminarEvento, "Eliminar evento", JOptionPane.OK_CANCEL_OPTION);
                        
                        if (resultado == JOptionPane.OK_OPTION){ eventosRecuperados.remove(seleccionado);
                        GestionClientes.guardarEventos(eventosRecuperados);
                        panelPantallaEliminarEvento.removeAll();
                        panelEliminarEvento.dispose();
                        } else if (resultado == JOptionPane.CANCEL_OPTION){panelPantallaEliminarEvento.removeAll();}
                    }
                }
            }
        });

            panelEliminarEvento.add(scroll);
            panelEliminarEvento.setVisible(true);
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Boton 3: Modificar evento
        
        JFrame panelModificarEvento = new JFrame("Modificar evento");
            JPanel panelPantallaModificarEvento = new JPanel();
            panelPantallaModificarEvento.setLayout(new BoxLayout(panelPantallaModificarEvento, BoxLayout.Y_AXIS)); 
            panelModificarEvento.setSize(300, 200);
            panelModificarEvento.setLocationRelativeTo(this); 
            
            
            
        
            ArrayList<Evento> eventosRecuperados = GestionClientes.cargarEventos();
            ArrayList<String> recuperadosArray = new ArrayList<>();

        for (Evento evento : eventosRecuperados) {
            String clave = evento.getTitulo(); 
            recuperadosArray.add(clave);
        }

        JList<String> lista = new JList<>(recuperadosArray.toArray(new String[0]));
        JScrollPane scroll = new JScrollPane(lista);
        lista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        lista.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent event) {
                if (event.getClickCount() == 2) {
                    int index = lista.locationToIndex(event.getPoint());
                    if (index >= 0) {
                        Evento seleccionado = eventosRecuperados.get(index);
                        
                        panelPantallaModificarEvento.removeAll();

                        JTextField campoModificarTitulo = new JTextField(seleccionado.getTitulo());
                        JTextField campoModificarTipo = new JTextField(seleccionado.getTipo());
                        JTextField campoModificarCalle = new JTextField(seleccionado.getDireccion().calle);
                        JTextField campoModificarNumero = new JTextField(String.valueOf(seleccionado.getDireccion().numero));
                        JTextField campoModificarCiudad = new JTextField(seleccionado.getDireccion().ciudad);
                        JTextField campoModificarCp = new JTextField(String.valueOf(seleccionado.getDireccion().cp));
                        JTextField campoModificarPrecio = new JTextField(String.valueOf(seleccionado.getPrecio()));
                        JTextField campoModificarFecha = new JTextField(seleccionado.getFecha().toString());
                        panelPantallaModificarEvento.add(new JLabel("Título: "));
                        panelPantallaModificarEvento.add(campoModificarTitulo);
                        panelPantallaModificarEvento.add(Box.createVerticalStrut(10));
                        panelPantallaModificarEvento.add(new JLabel("Tipo: "));
                        panelPantallaModificarEvento.add(campoModificarTipo);
                        panelPantallaModificarEvento.add(Box.createVerticalStrut(10));
                        panelPantallaModificarEvento.add(new JLabel("Calle: "));
                        panelPantallaModificarEvento.add(campoModificarCalle);
                        panelPantallaModificarEvento.add(Box.createVerticalStrut(10));
                        panelPantallaModificarEvento.add(new JLabel("Numero: "));
                        panelPantallaModificarEvento.add(campoModificarNumero);
                        panelPantallaModificarEvento.add(Box.createVerticalStrut(10));
                        panelPantallaModificarEvento.add(new JLabel("Ciudad: "));
                        panelPantallaModificarEvento.add(campoModificarCiudad);
                        panelPantallaModificarEvento.add(Box.createVerticalStrut(10));
                        panelPantallaModificarEvento.add(new JLabel("Código postal: "));
                        panelPantallaModificarEvento.add(campoModificarCp);
                        panelPantallaModificarEvento.add(Box.createVerticalStrut(10));
                        panelPantallaModificarEvento.add(new JLabel("Precio: "));
                        panelPantallaModificarEvento.add(campoModificarPrecio);
                        panelPantallaModificarEvento.add(Box.createVerticalStrut(10));
                        panelPantallaModificarEvento.add(new JLabel("Fecha: "));
                        panelPantallaModificarEvento.add(campoModificarFecha);
                        panelPantallaModificarEvento.add(Box.createVerticalStrut(20));
                        botonModificarImagen = new JButton("Modificar imagen");
                        panelPantallaModificarEvento.add(botonModificarImagen);
                        panelPantallaModificarEvento.add(Box.createVerticalStrut(10));
                        
                        botonModificarImagen.addActionListener(i -> {
                           JFileChooser selector = new JFileChooser();
                           selector.setDialogTitle("Selecciona una imagen");
                           selector.setAcceptAllFileFilterUsed(false);
                           selector.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png", "gif"));

                           int resultado = selector.showOpenDialog(null);
        
        

                           if (resultado == JFileChooser.APPROVE_OPTION) {
                           imagenCambiada = selector.getSelectedFile();
                           }     
                           });
                                             
                        int resultado = JOptionPane.showConfirmDialog(null, panelPantallaModificarEvento, "Modificar evento", JOptionPane.OK_CANCEL_OPTION);
                        
                        if (resultado == JOptionPane.OK_OPTION){
                        String tituloModificado = campoModificarTitulo.getText();
                        String tipoModificado = campoModificarTipo.getText();
                        String calleModificada = campoModificarCalle.getText();
                        int numeroModificado = Integer.parseInt(campoModificarNumero.getText());
                        String ciudadModificada = campoModificarCiudad.getText();
                        int cpModificado = Integer.parseInt(campoModificarCp.getText());
                        long precioModificado = Long.parseLong(campoModificarPrecio.getText());
                        LocalDate fechaModificada = leerFecha(campoModificarFecha.getText(), null);
                        
                        
                        try {
                            File archivo = new File(seleccionado.getRutaImagen());
                            System.out.println(archivo);

                            if (archivo.exists()) {
                                if (archivo.delete()) {
                                    System.out.println("Archivo eliminado correctamente.");
                                    } else {
                                    System.out.println("No se pudo eliminar el archivo.");
                                    }
                                    } else {
                                    System.out.println("El archivo no existe.");
                                    }
                            
                             BufferedImage original = ImageIO.read(imagenCambiada);
                             Image imagenEscalada = original.getScaledInstance(150, 150, Image.SCALE_SMOOTH);

                             BufferedImage imagenFinal = new BufferedImage(150, 150, original.getType() == 0 ? BufferedImage.TYPE_INT_RGB : original.getType());
                             Graphics2D g2d = imagenFinal.createGraphics();
                             g2d.drawImage(imagenEscalada, 0, 0, null);
                             g2d.dispose();

                             File carpetaDestino = new File("resources");
                             if (!carpetaDestino.exists()) carpetaDestino.mkdirs();

                             nombre = imagenCambiada.getName();
                             System.out.println(nombre);
                             extension = nombre.substring(nombre.lastIndexOf('.') + 1);

                             File archivoDestino = new File(carpetaDestino, nombre); // ("." + extension)
                             ImageIO.write(imagenFinal, extension, archivoDestino);

       //         JOptionPane.showMessageDialog(null, "Imagen escalada y guardada correctamente en:\n" + archivoDestino.getAbsolutePath());
            } catch (IOException o) {
                JOptionPane.showMessageDialog(null, "Error al procesar la imagen:\n" + o.getMessage());
            }
                        JOptionPane.showMessageDialog(null, 
                        "Evento modificado correctamente",
                        "Evento modificado",
                        JOptionPane.INFORMATION_MESSAGE);
                    
                        seleccionado.setTitulo(tituloModificado);
                        seleccionado.setTipo(tipoModificado);
                        seleccionado.getDireccion().setCalle(calleModificada);
                        seleccionado.getDireccion().setNumero(numeroModificado);
                        seleccionado.getDireccion().setCiudad(ciudadModificada);
                        seleccionado.getDireccion().setCp(cpModificado);
                        seleccionado.setPrecio(precioModificado);
                        seleccionado.setFecha(fechaModificada);
                        seleccionado.setRutaImagen("resources/" + nombre);

                        
                        GestionClientes.guardarEventos(eventosRecuperados);

                        }else if(resultado == JOptionPane.CANCEL_OPTION){panelPantallaModificarEvento.removeAll();}                      
                    }
                }
            }
        });

            panelModificarEvento.add(scroll);
            panelModificarEvento.setVisible(true);
            
    }//GEN-LAST:event_jButton3ActionPerformed

    public Evento registrarEvento(){
        String titulo = campoAnadirTitulo.getText();
        String tipo = campoAnadirTipo.getText();
        String calle = campoAnadirCalle.getText();
        int numero = Integer.parseInt(campoAnadirNumero.getText());
        String ciudad = campoAnadirCiudad.getText();
        int cp = Integer.parseInt(campoAnadirCp.getText());
        long precio = Long.parseLong(campoAnadirPrecio.getText());
        LocalDate fecha = leerFecha(campoAnadirFecha.getText(), null);
        String rutaImagen = "/resources/" + nombre;
        return new Evento(titulo,tipo,calle,numero,ciudad,cp,precio,0,fecha, rutaImagen);
        
        }
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Gestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
