/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.util.HashMap;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import proyectojava.Cliente;
import proyectojava.GestionClientes;
import static proyectojava.GestionClientes.usuarioActivo;

/**
 *
 * @author icesa
 */
public class VentanaGestionClientes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGestionClientes
     */
    public VentanaGestionClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración");
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jButton1.setText("Cambiar correo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jButton2.setText("Cambiar contraseña");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jButton3.setText("Cambiar datos de la tarjeta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jButton4.setText("Cambiar dirección");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Configuración usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(214, 214, 214))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Boton cambiar dirección
        JTextField campoCambioCalle = new JTextField(10);
            JTextField campoCambioNumero = new JTextField(10);
            JTextField campoCambioCiudad = new JTextField(10);
            JTextField campoCambioCodigo = new JTextField(10);
            JTextField campoContrasenaD = new JTextField(10);
            HashMap<String, Cliente> recuperados = GestionClientes.cargarClientes();
           
            JPanel panelCambioDireccion = new JPanel();
            panelCambioDireccion.setLayout(new BoxLayout(panelCambioDireccion,BoxLayout.Y_AXIS));
            panelCambioDireccion.add(new JLabel("Nueva calle: "));
            panelCambioDireccion.add(campoCambioCalle);
            panelCambioDireccion.add(Box.createVerticalStrut(10));
            panelCambioDireccion.add(new JLabel("Nuevo número: "));
            panelCambioDireccion.add(campoCambioNumero);
            panelCambioDireccion.add(Box.createVerticalStrut(10));
            panelCambioDireccion.add(new JLabel("Nueva ciudad: "));
            panelCambioDireccion.add(campoCambioCiudad);
            panelCambioDireccion.add(Box.createVerticalStrut(10));
            panelCambioDireccion.add(new JLabel("Nuevo código: "));
            panelCambioDireccion.add(campoCambioCodigo);
            panelCambioDireccion.add(Box.createVerticalStrut(10));
            panelCambioDireccion.add(new JLabel("Contraseña: "));
            panelCambioDireccion.add(campoContrasenaD);
            
            int resultadoD = JOptionPane.showConfirmDialog(null, panelCambioDireccion, "Cambio de dirección", JOptionPane.OK_CANCEL_OPTION);
            String calle = campoCambioCalle.getText();
            int numeroD = Integer.parseInt(campoCambioNumero.getText());
            String ciudadD = campoCambioCiudad.getText();
            int codigo = Integer.parseInt(campoCambioCodigo.getText());
            String contrasenaD = campoContrasenaD.getText();
            
            if (resultadoD == JOptionPane.OK_OPTION && (calle.isEmpty() || ciudadD.isEmpty() || contrasenaD.isEmpty())){
            JOptionPane.showMessageDialog(this, "Por favor, introduce los datos", "Datos no introducidos", HEIGHT);}
            else if (resultadoD == JOptionPane.OK_OPTION && (!calle.isEmpty() && !ciudadD.isEmpty() && !contrasenaD.isEmpty())){
                if (contrasenaD.equals(usuarioActivo.getContrasena())){
                recuperados.get(usuarioActivo.getCorreo()).getDireccion().setCalle(calle);
                recuperados.get(usuarioActivo.getCorreo()).getDireccion().setNumero(numeroD);
                recuperados.get(usuarioActivo.getCorreo()).getDireccion().setCiudad(ciudadD);
                recuperados.get(usuarioActivo.getCorreo()).getDireccion().setNumero(codigo);
                GestionClientes.guardarClientes(recuperados);
                System.out.println(recuperados);
                JOptionPane.showMessageDialog(this, "Cambio de dirección", "Has actualizado dirección", JOptionPane.INFORMATION_MESSAGE);
                return;
            } JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "La contraseña no coincide", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Boton cambiar correo
            JTextField campoCorreo = new JTextField(10);
            JTextField campoContrasena = new JTextField(10);
            HashMap<String, Cliente> recuperados = GestionClientes.cargarClientes();

            JPanel panelCambioContrasena = new JPanel();
            panelCambioContrasena.setLayout(new BoxLayout(panelCambioContrasena, BoxLayout.Y_AXIS)); 
            panelCambioContrasena.add(new JLabel("Nuevo correo: "));
            panelCambioContrasena.add(campoCorreo);
            panelCambioContrasena.add(Box.createVerticalStrut(10));  
            panelCambioContrasena.add(new JLabel("Contraseña:"));
            panelCambioContrasena.add(campoContrasena);

            int resultado = JOptionPane.showConfirmDialog(null, panelCambioContrasena, "Cambio de contraseña", JOptionPane.OK_CANCEL_OPTION);
            String usuario = campoCorreo.getText();
            String contrasena = campoContrasena.getText();

            if (resultado == JOptionPane.OK_OPTION && (usuario.isEmpty() || contrasena.isEmpty())) {
            JOptionPane.showMessageDialog(this, "Por favor, introduce los datos");

            } else if(resultado == JOptionPane.OK_OPTION && !usuario.isEmpty() && !contrasena.isEmpty()){
                if (contrasena.equals(usuarioActivo.getContrasena()) && (usuarioActivo.getCorreo().endsWith("@gmail.com") || usuarioActivo.getCorreo().endsWith("@hotmail.com"))){
                    recuperados.get(usuarioActivo.getCorreo()).setCorreo(usuario);
                    Cliente cliente = recuperados.get(usuarioActivo.getCorreo());
                    recuperados.remove(usuarioActivo.getCorreo());
                    recuperados.put(usuario, cliente);
                    GestionClientes.guardarClientes(recuperados);
                    System.out.println(usuario);
                    System.out.println(recuperados);

                    JOptionPane.showMessageDialog(this, "Cambio de correo", "Has actualizado tu direccion de correo correctamente", JOptionPane.INFORMATION_MESSAGE);
                    }
                else if(!contrasena.equals(usuarioActivo.getContrasena())){
                JOptionPane.showMessageDialog(this, "La contraseña es incorrecta, por favor, vuelve a introducir los datos", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);}
                
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Boton cambiar datos de la tarjeta
         JTextField campoCambioNombreT = new JTextField(10);
            JTextField campoCambioNumeroT = new JTextField(10);
            JTextField campoCambioFechaT = new JTextField(10);
            JTextField campoCambioContrasenaT = new JTextField(10);
            HashMap<String, Cliente> recuperados = GestionClientes.cargarClientes();

            JPanel panelCambioTarjeta = new JPanel();
            panelCambioTarjeta.setLayout(new BoxLayout(panelCambioTarjeta, BoxLayout.Y_AXIS)); 
            panelCambioTarjeta.add(new JLabel("Tarjeta de credito"));
            panelCambioTarjeta.add(Box.createVerticalStrut(10));  
            panelCambioTarjeta.add(new JLabel("Nuevo titular de la tarjeta: "));
            panelCambioTarjeta.add(campoCambioNombreT);
            panelCambioTarjeta.add(Box.createVerticalStrut(10));  
            panelCambioTarjeta.add(new JLabel("Nuevo número de tarjeta: "));
            panelCambioTarjeta.add(campoCambioNumeroT);
            panelCambioTarjeta.add(Box.createVerticalStrut(10)); 
            panelCambioTarjeta.add(new JLabel("Nueva fecha de caducidad de tarjeta: "));
            panelCambioTarjeta.add(campoCambioFechaT);
            panelCambioTarjeta.add(Box.createVerticalStrut(10));
            panelCambioTarjeta.add(new JLabel("Contraseña: "));
            panelCambioTarjeta.add(campoCambioContrasenaT);
                       
            int resultadoT = JOptionPane.showConfirmDialog(null, panelCambioTarjeta, "Cambio de tarjeta", JOptionPane.OK_CANCEL_OPTION);
            String nombreT = campoCambioNombreT.getText();
            String numeroT = campoCambioNombreT.getText();
            String fechaT = campoCambioNombreT.getText();
            String contrasenaT = campoCambioContrasenaT.getText();
            
            if (resultadoT == JOptionPane.OK_OPTION && (nombreT.isEmpty() || numeroT.isEmpty() || fechaT.isEmpty() || contrasenaT.isEmpty())) {
            JOptionPane.showMessageDialog(this, "Datos no introducidos","Por favor, introduce los datos",JOptionPane.INFORMATION_MESSAGE);
            } else if (resultadoT == JOptionPane.OK_OPTION && (!nombreT.isEmpty() && !numeroT.isEmpty() && !fechaT.isEmpty() && !contrasenaT.isEmpty())){ 
                if (contrasenaT.equals(usuarioActivo.getContrasena())){
                    System.out.println(recuperados);
                    recuperados.get(usuarioActivo.getCorreo()).getTarjeta().setNombre_titular(nombreT);
                    recuperados.get(usuarioActivo.getCorreo()).getTarjeta().setNumero_tarjeta(numeroT);
                    recuperados.get(usuarioActivo.getCorreo()).getTarjeta().setFecha_caducidad(fechaT);
                    GestionClientes.guardarClientes(recuperados);
                    System.out.println(recuperados);
                    JOptionPane.showMessageDialog(this, "Cambio de tarjeta", "La tarjeta se ha guardado correctamente", JOptionPane.INFORMATION_MESSAGE);
                
                } else if (numeroT.length() > 16){JOptionPane.showMessageDialog(this, "Formato de tarjeta inválido", "El número de tarjeta tiene que contener 16 dígitos, por favor, vuelve a introducirla", JOptionPane.ERROR_MESSAGE);}
                else  {JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "Las contraseñas no coinciden, por favor, vuelve a introducirla", JOptionPane.ERROR_MESSAGE);}
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Boton cambiar contraseña
         JTextField campoContrasena = new JTextField(10);
            JTextField campoCambioContrasena = new JTextField(10);
            JTextField campoCambioContrasenaV = new JTextField(10);
            HashMap<String, Cliente> recuperados = GestionClientes.cargarClientes();
            
            JPanel panelCambioContrasena = new JPanel();
            panelCambioContrasena.setLayout(new BoxLayout(panelCambioContrasena, BoxLayout.Y_AXIS));
            panelCambioContrasena.add(new JLabel("Contraseña actual: "));
            panelCambioContrasena.add(campoContrasena);          
            panelCambioContrasena.add(Box.createVerticalStrut(10));
            panelCambioContrasena.add(new JLabel("Nueva contraseña: "));
            panelCambioContrasena.add(campoCambioContrasena); 
            panelCambioContrasena.add(Box.createVerticalStrut(10));
            panelCambioContrasena.add(new JLabel("Repetir nueva contraseña: "));
            panelCambioContrasena.add(campoCambioContrasenaV); 
            
            int resultadoC = JOptionPane.showConfirmDialog(this, panelCambioContrasena, "Cambio de contraseña", JOptionPane.OK_CANCEL_OPTION);
            String contrasena = campoContrasena.getText();
            String nuevaContrasena = campoCambioContrasena.getText();
            String nuevaContrasenaV = campoCambioContrasenaV.getText();
            
            if (resultadoC == JOptionPane.OK_OPTION && (contrasena.isEmpty() || nuevaContrasena.isEmpty() || nuevaContrasenaV.isEmpty())) {
            JOptionPane.showMessageDialog(this, "Datos no introducidos","Por favor vuelve a introducir los datos", JOptionPane.INFORMATION_MESSAGE);
            } else if (resultadoC == JOptionPane.OK_OPTION && (!contrasena.isEmpty() && !nuevaContrasena.isEmpty() && !nuevaContrasenaV.isEmpty())){
                if (contrasena.equals(usuarioActivo.getContrasena())){
                    if(nuevaContrasena.equals(nuevaContrasenaV) && (nuevaContrasena.length() > 7 && nuevaContrasena.length() > 7)){
                        recuperados.get(usuarioActivo.getCorreo()).setContrasena(contrasena);
                        GestionClientes.guardarClientes(recuperados);
                        System.out.println(recuperados);
                        JOptionPane.showMessageDialog(this, "Cambio de contraseña", "Has actualizado tu contraseña", JOptionPane.INFORMATION_MESSAGE);
                        return;
                        
                    } if (nuevaContrasena.length() > 7 && nuevaContrasenaV.length() > 7){
                        if (!nuevaContrasena.equals(nuevaContrasenaV)){
                            JOptionPane.showMessageDialog(this, "Contraseñas desiguales", "La nueva contraseña no coincide, por favor, vuelve a introducirlas", JOptionPane.INFORMATION_MESSAGE);
                            return;
                            
                }
            }if(nuevaContrasena.length() < 8 || nuevaContrasenaV.length() < 8){ JOptionPane.showMessageDialog(this, "Formato de contraseña inválido", "La nueva contraseña tiene que contener al menos 8 caracteres, por favor, vuelve a introducirlas", JOptionPane.ERROR_MESSAGE);}
            }else {JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "La contraseña no coincide", JOptionPane.ERROR_MESSAGE);}
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGestionClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
